- hosts: server
  vars:
    image: gokillcrew/web-games
  tasks:
    - name: instal python-docker di ubuntu
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - python3
        - python3-docker
      when: ansible_facts['os_family'] == "Debian"

    - name: instal pyton-docker di centos
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-docker
      when: ansible_facts['os_family'] == "RedHat"

    - name: pull image dari docker hub
      docker_image:
        name: "{{ image }}"
        state: present
        force: yes

    - name: run container
      docker_container:
        name: docker-web-games       
        image: "{{ image }}"
        state: started
        published_ports:
          - 10012:80
        recreate: yes
